# search parameters
SEARCH_MAX_RESULTS = 10
TEMPERATURE = 0.0
SEED = 1234
USE_TEXT_SEARCH = "hybrid"
USE_VECTOR_SEARCH = "hybrid"
USE_SEMANTIC_RANKER = True
USE_SEMANTIC_CAPTIONS = False
MINIMUM_SEARCH_SCORE = 0.022
MINIMUM_RERANKER_SCORE = 2.21
COSINE_SIMILARITY_THRESHOLD = 0.90
VECTOR_WEIGHT = 1.75

# token limit parameters
QUERY_RESPONSE_MAX_TOKENS = 100
CHAT_RESPONSE_MAX_TOKENS = 512

# language detection parameter
LANG_SCORE_THRESHOLD = 0.7
